name: Weekly Update

on:
  schedule:
    - cron: '0 7 * * SAT'
  workflow_dispatch:

jobs:
  update-dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install requests packaging

      - name: Run update script
        run: python tools/update_dockerfile.py

      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name 'ironashram'
          git config --global user.email 'sysdadmin@m1k.cloud'
          git add Dockerfile
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update Dockerfile with latest versions"
            git push
            new_tag=$(python tools/bump_version.py)
            git tag $new_tag
            git push origin $new_tag
          fi
